# -*- coding: utf-8 -*-
"""gnit1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKiuf7fSawE8Y7ainqmPdH7tFWW87BwM
"""

from google.colab import drive
drive.mount("/content/drive")

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d sumanbera19/bengaluru-house-price-dataset

import zipfile

with zipfile.ZipFile("bengaluru-house-price-dataset.zip") as z:
  z.extractall("House")

import numpy as np
import pandas as pd

data=pd.read_csv("/content/House/bengaluru_house_prices.csv")
df=pd.DataFrame(data)
df

df.info()

df.describe()

df.isnull().sum().sum()

df.size

df1_1=df.dropna()
df1_1.size

df_2=df.fillna(100)
df_2.size

df

df.isnull().sum()

df.shape

a=df.isnull().sum()/df.shape[0]*100
a



b=a[a>17].keys()
b

df.drop(b,axis=1,inplace=True)

df

df.isnull().sum()

cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

num_col=df.select_dtypes(include=["int64","float64"]).columns.tolist()
num_col

from sklearn.impute import SimpleImputer

cat_clean=SimpleImputer(strategy="most_frequent")
num_clean=SimpleImputer(strategy="mean")

df[cat_col]=cat_clean.fit_transform(df[cat_col])
df[num_col]=num_clean.fit_transform(df[num_col])

df.isnull().sum().sum()

df.size

df

df['price']=df['price']*100000
df

print("2 BHK")

a=df['size'].apply(lambda x:int(x.split(" ")[0]))
a

df.insert(3,"BHK",a)

df

df.drop("size",axis=1,inplace=True)

df

df.drop(["area_type","availability"],axis=1,inplace=True)

df

# df.insert(5,"price/sqft",df["price"]/df['total_sqft'])

df["price"].dtypes

df['total_sqft'].dtypes

def check(x):
  try:
   float(x)
   return True
  except:
    return False

z=df[~df['total_sqft'].apply(check)]

z

def convert(x):
  if isinstance(x,str):
    x=x.strip()
    if "-" in x:
      try:
        a,b=x.split("-")
        return (float(a)+float(b))/2
      except:
        return float(x)
    try:
      return float(x)
    except:
      return np.nan
  return np.nan

df['total_sqft']=df['total_sqft'].apply(convert)

df.shape

df.isnull().sum()

df_1=df.dropna(inplace=True)

df_1

df_1

df

df_2=df.dropna(subset=["total_sqft"],inplace=True)

df_2

df_2

df.insert(5,"price/sqft",df["price"]/df['total_sqft'])

df

from sklearn.datasets import load_breast_cancer
c=load_breast_cancer()

d={
    "name":"amit",
    "roll":1
}
d

c.keys()

c.data

c.target

c.target_names

c.feature_names

df_c=pd.DataFrame(np.c_[c.data,c.target],columns=list(c.feature_names)+["output"])
df_c

df_c.shape

df_c.isnull().sum().sum()

x=df_c.iloc[ : , :-1]

x.shape

x

y=df_c.iloc[ : ,-1]

y.shape

y

a=np.array([1,2,3,4,5])
a

a[1:3]

a[-5]

x

y

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

x_train.shape

y_train.shape

def area(x,y):
  print(f"area of the room is :{x*y}")

area(10,12)



x_test.shape

y_test.shape

x_train

x_test

y_train

y_test

from sklearn.preprocessing import MinMaxScaler , StandardScaler

STD=StandardScaler()
MM=MinMaxScaler()

x_train_std=STD.fit_transform(x_train)

x_train_std

df_c_sc_std=pd.DataFrame(np.c_[x_train_std],columns=list(c.feature_names))
df_c_sc_std

x_train_minMax=MM.fit_transform(x_train)

df_c_sc_mm=pd.DataFrame(np.c_[x_train_minMax],columns=list(c.feature_names))
df_c_sc_mm

y_train

